#!/bin/bash
#intented to allow resizong bspwm windows by dragging them from window gap. Requires rootmenu

eval $(xdotool getmouselocation --shell)
IFS=" " read -a window <<< $(wattr whxy $(pfw))

# location of each side of focused window
up=$(expr "${window[3]}")
down=$(expr "${window[3]}" + "${window[1]}")
left=$(expr "${window[2]}")
right=$(expr "${window[2]}" + "${window[0]}")

# maximum co-ordinates of desired mouse location, 5 pixels inside window
maxx=$(echo "$right - 5" | bc)
minx=$(echo "$left + 5" | bc)
miny=$(echo "$up + 5" | bc)
maxy=$(echo "$down - 5" | bc)

#set final position to current or at most within window
XP=$X
[[ $XP -gt $maxx ]] && XP=$maxx
[[ $XP -lt $minx ]] && XP=$minx
YP=$Y
[[ $YP -lt $miny ]] && YP=$miny
[[ $YP -gt $maxy ]] && YP=$maxy

xdotool mousemove --sync $XP $YP;
bspc pointer -g resize_corner
