#!/bin/bash
#intented to allow resizong bspwm windows by dragging them from window gap. Requires rootmenu

eval $(xdotool getmouselocation --shell)
IFS=" " read -a window <<< $(wattr whxy $(pfw))

# location of each side of focused window
miny=$(("${window[3]}" + 5))
maxy=$(("${window[3]}" + "${window[1]}" - 5))
minx=$(("${window[2]}" + 5))
maxx=$(("${window[2]}" + "${window[0]}" - 5))

#set final position to current or at most within window
XP=$X
[[ $XP -gt $maxx ]] && XP=$maxx
[[ $XP -lt $minx ]] && XP=$minx
YP=$Y
[[ $YP -lt $miny ]] && YP=$miny
[[ $YP -gt $maxy ]] && YP=$maxy

xdotool mousemove --sync $XP $YP;
xdotool keydown super;
xdotool mousedown 
bspc pointer -g resize_corner
