#!/usr/bin/env bash
# script to enable hibernation noninteractively, based on powerdown-functions
shopt -s nullglob extglob

swapfilesize=${1-4G}
hibernate_offset() {
    filefrag -v /swapfile | awk 'NR==4 {print $4}' | tr -d .
}

root_part() {
    grep " / " /etc/fstab | awk '{print $1}' | sed 's/PARTUUID/UUID/' | sed 's/PARTUUID/UUID/
}

has_swap_part () {
    grep -qs swap /etc/fstab
}

can_suspend_to_disk () {
    [[ -f /swapfile ]] || has_swap_part
}

swap_part() {
    awk '$3=="swap" {print $1; exit}' /etc/fstab
}

resume_boot_option() {
    if [[ -f /swapfile ]]; then
        echo "resume=$(root_part) resume_offset=$(hibernate_offset)"
    elif has_swap_part; then
        echo "resume=$(swap_part)"
    fi
}

# lock the file until the script finishes
lock() {
    local LOCK=/tmp/hibernator.lock
    if ! mkdir "$LOCK" 2> /dev/null; then
        echo "Working... $LOCK"
        exit
    fi
    trap "rm -rf $LOCK" EXIT
}

if [[ $EUID != 0 ]]; then
    echo "[hibernator] must be run as root"
    exit 1
fi

has_resume_hook () {
    grep -qs resume /etc/mkinitcpio.conf || grep -qs systemd /etc/mkinitcpio.conf
}
#############################
lock

if ! can_suspend_to_disk; then
    fallocate -l $swapfilesize /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile	swap	swap	defaults	0	0' >> /etc/fstab
    #backup old /etc/default/grub
    cp /etc/default/grub /etc/default/grub.old \
    && sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT/ s/quiet/$(resume_boot_option) quiet/' /etc/default/grub \
    && grub-mkconfig -o /boot/grub/grub.cfg
		if ! has_resume_hook; then
			cp /etc/mkinitcpio.conf /etc/mkinitcpio.conf.old \
			&&sed -i s/'filesystem/filesystem resume'/g /etc/mknitcpio.conf
			for kernel in $(mhwd-kernel -li | sed '1,2d' | awk '{print $2}'); do
			mkinitcpio -p $kernel
		done
fi
fi
