#!/bin/sh
# Get the necessary info
# combination of MouseLaunch and pseudo_automatic_mode 

eval $(xdotool getmouselocation --shell)
IFS=" " read -a window <<< $(xwinfo -g $(pfw))

# Distance to each side
up=$(expr "$Y" - "${window[3]}")
down=$(expr "${window[3]}" + "${window[1]}" - "$Y" )
left=$(expr "$X" - "${window[2]}")
right=$(expr "${window[2]}" + "${window[0]}" - "$X" )

# Determine if split should be vertical or horizontal
wattr wh $(pfw) | {
	read width height
	if [ $width -gt $height ] ; then
		split=horizontal
	else
		split=vertical
	fi
}

# Determine which window edge is closer
if [ "$split" = "vertical" ]; then
    if [ "$up" -lt "$down" ]; then
        dir_final=up
    else 
        dir_final=down
    fi
else
    if [ "$left" -lt "$right" ]; then
        dir_final=left
    else 
        dir_final=right
    fi
fi
done

# Send the presel signal
bspc window -p cancel # Necessary if you have set auto_cancel to true
bspc window -p $dir_final
