#!/bin/bash


if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc

available=$(pacman -Slq)
explicitinst=$(pacman -Qqen)
installed=$(pacman -Qq)
orphans=$(pacman -Qtdq)
#set default terminal

term=${TERMINAL:-urxvt}

case $option in
    Install           ) $term sudo pacman -S $($available | dmenu -p 'select package to install');;
    Uninstall         ) $term sudo pacman -Rsn $($installed | dmenu -p 'select package to remove);;
    Update             ) $term sudo pacman -Syu;;
    Downgrade          ) $term sudo downgrade $installed;;
    Backup          ) $term $explicitinst > .$HOME/packagebackup;;
    Clean               ) exec dwm;;
    RemoveOrphan     ) $term sudo pacman -Rsn $($orphans | dmenu -p 'Select orphan to remove';;
    RemoveOrphans               ) $term sudo pacman -Rsn $orphans;;
    FullClean           ) exec startfluxbox;;
    CheckUpdates             ) exec gnome-session;;
    RestoreBackup     ) exec gnome-session --session=gnome-classic;;
    EditMirrorlist           ) exec i3;;
    RankMirrors             ) exec icewm-session;;
    ConfigurePacman               ) exec jwm;;
    # No known session, try to run it as command
    *) exec $1;;
esac 
